package com.medverse.backend.utils.enumeration;

public enum NotificationType {
    APPOINTMENT_REQUEST_CREATED,
    APPOINTMENT_REQUEST_APPROVED,
    APPOINTMENT_REQUEST_REJECTED,
    APPOINTMENT_REQUEST_CANCELLED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    PRESCRIPTION_FINALIZED,
    AI_SAFETY_ALERT,
    SYSTEM
}