package com.medverse.backend.utils.enumeration;

public enum NotificationType {
    APPOINTMENT_REQUEST_CREATED,
    APPOINTMENT_REQUEST_APPROVED,
    APPOINTMENT_REQUEST_REJECTED,
    APPOINTMENT_REQUEST_CANCELLED,

    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_NO_SHOW,

    MEDICAL_RECORD_COMPLETED,

    PRESCRIPTION_FINALIZED,
    PRESCRIPTION_CANCELLED,

    AI_SAFETY_ALERT,
    SYSTEM
}